### ISSUE TITLE
Support for regular workflows?

### ISSUE THREAD

**Issue by gj250116** [npalm/action-docs#240]
Is there support for workflows apart from regular actions? 
For example:
```
name: Workflow

on:
  workflow_call:
    inputs:
      input1:
        description: "Input1"
        required: false

    outputs:
      output1:
        description: "Output1"
        required: false

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: 'Checkout' 
        uses: actions/checkout@v2
```

This errors out with: `Cannot read properties of undefined (reading 'using')`
