### ISSUE TITLE
Multiline description

### ISSUE THREAD

**Issue by jcook-uptycs** [npalm/action-docs#344]
The inputs and outputs tables do not handle multi line descriptions well.

Is there an option for not using a table for inputs and outputs?

```yaml
name: test
description: |
  Test action to see how action-docs handles
  Multiline
  descriptions
inputs:
  test:
    default: test
    description: |
      Test action to see how action-docs handles
      Multiline
      descriptions
outputs:
  test:
    description: |
      Test action to see how action-docs handles
      Multiline
      descriptions

runs:
  using: 'docker'
  image: 'Dockerfile'
```
