### ISSUE TITLE
pipe `|` is not properly escaped

### ISSUE THREAD

**Issue by npalm** [npalm/action-docs#569]
Having | symbols in input or output description is breaking the table creation due to the lack of a proper escape.

**Comment by Gonzalo44r** [comment]
Hello Niek, I'm currently having trouble with this. Although I found a workaround for my work setup, it would be nice to have this fixed.
In my action I have this input:
```
inputs:
  branch:
    description: 'Branch'
    required: false
    default: ${{ github.base_ref || github.ref_name  }}
```
The problem is that I cannot change that default value.
The result is this:
```
| `branch` | <p>Branch</p> | `false` | `${{ github.base_ref || github.ref_name  }}` |
```` 
![image](https://github.com/npalm/action-docs/assets/114468907/0d05abaa-f37f-4d3c-93ba-6e0cb6cfb401)

Just to remember we also have this section (wich is good):
![image](https://github.com/npalm/action-docs/assets/114468907/5a3106c7-eb02-4ff6-b8a0-69d68b338024)


### Solution
The script could replace `|` to `\|`, only when creating the table, at least at the **default** parameters.

Thank you.
