### ISSUE TITLE
Does not appear to work with Workflows

### ISSUE THREAD

**Issue by arwhita** [npalm/action-docs#574]
The documentation states that workflows are supported.

I've attempted this with my own workflows, and also with workflows contained within this project itself. Workflows do not appear to be supported, and always render the same generic block of text.

### To Replicate

Run the following:

```
action-docs -s .github/workflows/dependabot.yml
```

### Result

````
## Usage

```yaml
jobs:
  job1:
    uses: ***PROJECT***@***VERSION***
    with:
```

````

### Expected

Something showing actual details of jobs, steps, etc.
