### ISSUE TITLE
Usage can't show paths for workflow/action files

### ISSUE THREAD

**Issue by glungley** [npalm/action-docs#654]
For reusable workflows or custom actions which aren't at the root of the repository. The usage should include the path to the workflow/action yaml file. E.g.

```
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
```
