### ISSUE TITLE
Error when using workflow_call trigger

### ISSUE THREAD

**Issue by Jonmacb** [npalm/action-docs#659]
I receive the below error when running on a workflow file with a trigger of workflow_call. I've tested multiple workflow files and if I change it to another trigger such as push it works as expected. I'm using version 2.4.2.

`Cannot read properties of undefined (reading 'replace')`

eg.

```yaml
on:
  workflow_call:
    inputs:
      IMAGEDIR:
        required: true
        type: string
      IMAGENAME:
        required: false
        type: string
        default: ""
```
